version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: '${DATABASE_URL}'
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5434'

volumes:
  pgdata:
